version: '3'
services:
    dbserver:  
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=microblog
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=password
        volumes:
            - '/var/lib/mysql:/var/lib/mysql'
    prod:
        image: sandrajinnevall/microblog:latest2
        build: 
            dockerfile: docker/Dockerfile_prod
            context: .
        container_name: 'microblog'
        environment:
            - FLASK_APP=microblog.py
            - SECRET_KEY=my-secret-key
            - DATABASE_URL=mysql+pymysql://microblog:password@dbserver:3306/microblog 
        ports:
            - 8000:5000
        links:
            - dbserver
        restart: always
    test:
        volumes:
            - .:/home/microblog
            - /home/microblog/venv
        build: 
            context: .
            dockerfile: ./docker/Dockerfile_test