global:
  scrape_interval:  5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: 'mysql'
    static_configs:
      - targets: ['13.69.214.228:9104']
  # - job_name: "flaskapp"
  #   static_configs_
  #     - targets: ['{{ groups['appServer'][0] }}:8000']