version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: sandrajinnevall/microblog
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest2 -f ./docker/Dockerfile_prod .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME:latest2
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest2
  publish-tag:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest2 $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest2
            docker push $IMAGE_NAME:$IMAGE_TAG

  deploy-latest:
    executor: docker-publisher
    steps:
      - checkout
      - run:
         name: Install venv
         command: |
             sudo apt-get install python3.8-venv
             python3.8 -m venv .venv
      - run: echo "source ~/project/.venv/bin/activate" >> $BASH_ENV 
      - run:
         name: Install dependencies
         command: |
             pip3 install --upgrade setuptools
             pip3 install --upgrade pip
             pip3 install wheel
             make install-deploy
             pip3 install ansible[azure]
      - run:
          name: Deploy appServer
          command: |
              cd ansible
              ansible-playbook gather_vm_instances.yml appServer.yml
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-latest:
         requires:
           - publish-latest
         filters:
           branches:
             only: master
  build-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-tag:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/