FROM python:3.8

WORKDIR /home/microblog
COPY test.sh .
COPY requirements ./requirements

RUN python -m venv .venv \
&& .venv/bin/pip3 install -r requirements/test.txt \
&& .venv/bin/pip3 install py pytest coverage pylint \
&& chmod +x test.sh

ENTRYPOINT [ "./test.sh" ]